# Walmart Sales Data – Data Cleaning & Feature Engineering

## Business Context
Walmart operates multiple retail branches across cities and product categories.
This notebook prepares a clean, analysis-ready dataset by performing
data validation, cleaning, and feature engineering to support
SQL-based analysis and BI dashboards.

In [1]:
import pandas as pd

In [2]:
# Load raw data
df = pd.read_csv('../data/raw/Walmart.csv', encoding_errors='ignore')

In [10]:
# Dataset overview
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48

In [11]:
df.shape

(10000, 11)

In [12]:
df.describe()

        invoice_id     quantity        rating  profit_margin
count  10000.00000  9969.000000  10000.000000   10000.000000
mean    5000.50000     2.355602      5.830170       0.393813
std     2886.89568     1.605455      1.764097       0.090656
min        1.00000     1.000000      3.000000       0.180000
25%     2500.75000     1.000000      4.000000       0.330000
50%     5000.50000     2.000000      6.000000       0.330000
75%     7500.25000     3.000000      7.000000       0.480000
max    10000.00000    10.000000     10.000000       0.570000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10000 non-null  int64
 1   Branch          10000 non-null  object
 2   City            10000 non-null  object
 3   category        10000 non-null  object
 4   unit_price      9969 non-null   object
 5   quantity        9969 non-null   float64
 6   date            10000 non-null  object
 7   time            10000 non-null  object
 8   payment_method  10000 non-null  object
 9   rating          10000 non-null  float64
 10  profit_margin   10000 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 937.5+ KB

## Data Quality Assessment
We check for:
- Duplicate transactions
- Missing values in critical fields
- Incorrect data types

In [14]:
# Duplicate check
df.duplicated().sum()

np.int64(0)

In [15]:
# Remove duplicates
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [16]:
df.shape

(10000, 11)

In [17]:
# Missing values
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [18]:

#Droppping all rows with missing records
df.dropna(inplace=True)

# verify
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [19]:
df.shape

(9969, 11)

In [20]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

## Data Cleaning Summary
- Removed duplicate transactions
- Dropped rows with missing price or quantity
- Retained valid invoice-level records

## Price Standardization
Unit prices contain currency symbols and are converted to numeric format.

In [21]:
df['unit_price'] = df['unit_price'].astype(str).str.replace('$', '', regex=False).astype(float)

In [22]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48

In [23]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

## Feature Engineering
Created features to support time-based, operational, and revenue analysis.

In [24]:
# Total transaction value
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48,604.17

In [25]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='object')

In [26]:
df.columns = df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='object')

In [27]:
# Date and time parsing
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S').dt.time

In [28]:
# Time-based features
df['hour'] = pd.to_datetime(df['time'], format='%H:%M:%S').dt.hour
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['weekday'] = df['date'].dt.day_name()
df['is_weekend'] = df['weekday'].isin(['Saturday', 'Sunday'])

In [29]:
df[['date', 'time', 'hour', 'day', 'month', 'year', 'weekday', 'is_weekend']].head()

        date      time  hour  day  month  year   weekday  is_weekend
0 2019-01-05  13:08:00    13    5      1  2019  Saturday        True
1 2019-03-08  10:29:00    10    8      3  2019    Friday       False
2 2019-03-03  13:23:00    13    3      3  2019    Sunday        True
3 2019-01-27  20:33:00    20   27      1  2019    Sunday        True
4 2019-02-08  10:37:00    10    8      2  2019    Friday       False

In [30]:
def shift(hour):
    """
    Classifies purchase time into business shifts
    for operational analysis.
    """
    if hour < 12:
        return 'Morning'
    elif hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'

df['shift'] = df['hour'].apply(shift)

In [31]:
df.head()

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total,hour,day,month,year,weekday,is_weekend,shift
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,2019-01-05,13:08:00,Ewallet,9.1,0.48,522.83,13,5,1,2019,Saturday,True,Afternoon
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,2019-03-08,10:29:00,Cash,9.6,0.48,76.40,10,8,3,2019,Friday,False,Morning
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,2019-03-03,13:23:00,Credit card,7.4,0.33,324.31,13,3,3,2019,Sunday,True,Afternoon
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,2019-01-27,20:33:00,Ewallet,8.4,0.33,465.76,20,27,1,2019,Sunday,True,Evening
4,5,WALM013,Irving,Sports and travel,86.31,7.0,2019-02-08,10:37:00,Ewallet,5.3,0.48,604.17,10,8,2,2019,Friday,False,Morning

In [32]:
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total',
       'hour', 'day', 'month', 'year', 'weekday', 'is_weekend', 'shift'],
      dtype='object')

In [33]:
df.shape

(9969, 19)

## Data Export
The processed dataset is saved for reuse in SQL analysis and visualization.

In [34]:
df.to_csv('../data/processed/walmart_featured_data.csv', index=False)