# Walmart Sales Data – SQL Integration

## Purpose
This notebook loads the cleaned dataset into PostgreSQL to enable
SQL-based business analysis, simulating an enterprise analytics workflow.

In [1]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

In [2]:
# Load processed data
df = pd.read_csv('../data/processed/walmart_featured_data.csv')
df.head()

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total,hour,day,month,year,weekday,is_weekend,shift
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,2019-01-05,13:08:00,Ewallet,9.1,0.48,522.83,13,5,1,2019,Saturday,True,Afternoon
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,2019-03-08,10:29:00,Cash,9.6,0.48,76.40,10,8,3,2019,Friday,False,Morning
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,2019-03-03,13:23:00,Credit card,7.4,0.33,324.31,13,3,3,2019,Sunday,True,Afternoon
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,2019-01-27,20:33:00,Ewallet,8.4,0.33,465.76,20,27,1,2019,Sunday,True,Evening
4,5,WALM013,Irving,Sports and travel,86.31,7.0,2019-02-08,10:37:00,Ewallet,5.3,0.48,604.17,10,8,2,2019,Friday,False,Morning

## Database Connection
Credentials are hidden for security reasons.

**Before running this notebook:**

1. Create a PostgreSQL database named `walmart_sales_db`
2. Update the connection string with your PostgreSQL username and password
3. Ensure PostgreSQL service is running

Example (psql):
CREATE DATABASE walmart_sales_db;

In [ ]:
DB_NAME = "walmart_sales_db"
USER = "your_username"
PASSWORD = "your_password"
HOST = "localhost"
PORT = "5432"

engine = create_engine(
    f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}"
)

## Load Data into PostgreSQL

In [4]:
df.to_sql(
    name='walmart',
    con=engine,
    if_exists='replace',
    index=False
)

969

## Validation Queries
Ensures the table is loaded correctly and ready for analysis.

In [5]:
pd.read_sql("SELECT COUNT(*) FROM walmart", engine)

   count
0   9969

In [6]:
pd.read_sql("SELECT * FROM walmart LIMIT 5", engine)

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total,hour,day,month,year,weekday,is_weekend,shift
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,2019-01-05,13:08:00,Ewallet,9.1,0.48,522.83,13,5,1,2019,Saturday,True,Afternoon
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,2019-03-08,10:29:00,Cash,9.6,0.48,76.40,10,8,3,2019,Friday,False,Morning
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,2019-03-03,13:23:00,Credit card,7.4,0.33,324.31,13,3,3,2019,Sunday,True,Afternoon
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,2019-01-27,20:33:00,Ewallet,8.4,0.33,465.76,20,27,1,2019,Sunday,True,Evening
4,5,WALM013,Irving,Sports and travel,86.31,7.0,2019-02-08,10:37:00,Ewallet,5.3,0.48,604.17,10,8,2,2019,Friday,False,Morning

The dataset is now available for advanced SQL analysis.